### ISSUE TITLE
Logging is a breaking change

### ISSUE THREAD

**Issue by raghu017** [asynkron/protoactor-go#1027]
With the introduction of logging in PR [#937](https://github.com/asynkron/protoactor-go/pull/937), a breaking change has been introduced that necessitates a major version change. Prior to this PR, there was no logging in place, and the current default logging level set to INFO diverges from the previous behavior.

Suggestions:

1. Default Logging Level: The logging feature should be disabled by default, preserving the prior behavior. Users who require this functionality can then enable it as per their needs.
2. Adjustable Logging Level: If logging is enabled, the default logging level should be set at a higher level such as ERROR or WARN. This approach will minimize the amount of logged data and prevent potential performance impacts.
3. Documentation: Provide examples in the documentation on how to change the logging level.

**Comment by MciReloaded** [comment]
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

https://semver.org/#spec-item-4
