### ISSUE TITLE
Mailbox empty statistics

### ISSUE THREAD

**Issue by samanbarghi** [asynkron/protoactor-go#103]
This line can be reached even when the mailbox is suspended and not empty : https://github.com/AsynkronIT/protoactor-go/blob/dev/mailbox/mailbox.go#L94

**Comment by rogeralsing** [comment]
Good catch!

**Comment by alex023** [comment]
Before execution, adding judge sentences?just like：
```code
if !m.suspended{
 for _, ms := range m.mailboxStats {
		ms.MailboxEmpty()
	}
}
```
