### ISSUE TITLE
Go coroutine thread safe

### ISSUE THREAD

**Issue by molixiaoge** [asynkron/protoactor-go#1039]
Hi, i run the example  actor-helloworld.The func  Receive(context actor.Context) {} called with different coroutine ,so I test 
concurrency map write,it work well.I want to know how it do work  thread safe with differenct gocourines?

**Comment by rogeralsing** [comment]
Yes, that is the whole point of it.
When there are one or more messages in the mailbox, the actor is scheduled on a goroutine.
Once the mailbox is empty, it goes back to idle, and the goroutine is released.
Once a new message arrives again, it is yet again scheduled onto a goroutine (a new one) 

But there are never ever more than one goroutine running for a given actor

**Comment by molixiaoge** [comment]
Thx . I understand now.
