### ISSUE TITLE
Is every actor  message Receiver run in they own goroutine ?

### ISSUE THREAD

**Issue by calvin2021y** [asynkron/protoactor-go#1049]
I want to do some action like Redis in receive func,  is this allowed ?

**Comment by rogeralsing** [comment]
An actor does not have a dedicated Go-routine, instead we schedule the actor onto a new Go-routine whenever the actor has messages in the mailbox.
once it is done, that Go-routine would end.

But it does guarantee that there is at most one Go-routine running per actor.
And yes, talking to Redis from an actor is fine
