### ISSUE TITLE
How can a member within a cluster be restarted?

### ISSUE THREAD

**Issue by Northward712** [asynkron/protoactor-go#1083]
When I use Etcd for clustering, after nodes A and B start up, closing A normally, and then restarting A, the existence of Remote.BlockedList causes node B to ignore A and not include it in the MemberList. What should I do at this point to ensure that node B can place the reconnected A into the MemberList?

![image](https://github.com/asynkron/protoactor-go/assets/37608723/af61871f-e590-4f4a-af6e-87878d1756c8)

**Comment by Northward712** [comment]
I'm sorry, I really can't understand why a normally closed node is added to the blocked list, leading to the inability to join the Member List after restarting.



![image](https://github.com/asynkron/protoactor-go/assets/37608723/3039814e-76a6-4702-8d45-d20bbac5bad6)

**Comment by rogeralsing** [comment]
It will not be the same member when it restarts. it will have a new ID
