### ISSUE TITLE
Can we also implement an `Unstash()` method?

### ISSUE THREAD

**Issue by potterdai** [asynkron/protoactor-go#271]
Can we also implement an `Unstash()` method? Restarting an actor to get all stashed messages makes no sense for me. If I stash messages to a certain point, I would want to call unstash to get them instead of restarting the actor. What do you think?

_Originally posted by @Chumper in https://github.com/AsynkronIT/protoactor-go/pull/251#issuecomment-464098379_

**Comment by PotterDai** [comment]
Also I think that we can implement the Stash and Timeout functionality similiar to the persistence mixins. That would make the actor really slim and we can compose additional functionality with mixins.
But maybe that is something for another PR.

_Originally posted by @Chumper in https://github.com/AsynkronIT/protoactor-go/pull/251#issuecomment-464100513_

**Comment by PotterDai** [comment]
@Chumper will do in a new PR

**Comment by rogeralsing** [comment]
I would very much like to see a mixin approach to stashing. so it is not a core concept of the actor itself but rather something that is plugged in.

Because the requirements or needs for stashing might differ for different projects.
and the Akka inspired One size fits all, feels wrong for me

**Comment by rogeralsing** [comment]
In the .NET version, we now have a "CaptureContext" which can be applied, and thus setting message, headers etc of the actor context.
This allows developers to easily build their own stashing behaviors by storing captured contexts.

In progress porting this over
