### ISSUE TITLE
[cluster] Should activating an existing grain be an issue ? Probably missing something here

### ISSUE THREAD

**Issue by otherview** [asynkron/protoactor-go#303]
Hi guys!

I'm having a lot of errors from : 

```
get PID failed with StatusCode: 3
```

Coming from :
```
fun := func() (*Noop, error) {
			pid, statusCode := cluster.Get(g.ID, "TheGrain")
			if statusCode != remote.ResponseStatusCodeOK {
				return nil, fmt.Errorf("get PID failed with StatusCode: %v", statusCode)
			}
```

From what I digged down - Wouldn't `ResponseStatusCodePROCESSNAMEALREADYEXIST` be an ok response ?

I'll try to simulate it, but I think its a race condition where 2 calls try to instantiate a new Grain with the same name ?

Thoughts ?

**Comment by potterdai** [comment]
Hi @otherview, thank you for testing! Could you describe more what you did when you encounter those errors? Actually, indeed it is OK response and the returned `pid` will be the existed PID. However it is not a normal sign if you encounter a lot of those errors...

**Comment by otherview** [comment]
I'm not sure how it's happening - here's my guess:

This seems to happen to only in my `TrackerGrain` - Which broadcasts messages, where other grains register with, etc.. So there a lot of requests coming into this fellow.


 - This is the only place where that Response Code gets generated:
https://github.com/AsynkronIT/protoactor-go/blob/f10464bf5394a4121d309e7e49fddeb9271c9cf8/remote/activator_actor.go#L102-133

My guess is that :

1- Two or more calls are made - They reach here at the same time:
```
                         pid, statusCode := cluster.Get(g.ID, "TheGrain")
			if statusCode != remote.ResponseStatusCodeOK {
				return nil, fmt.Errorf("get PID failed with StatusCode: %v", statusCode)
			}
```
2- And both get into `pid, statusCode := cluster.Get(g.ID, "TheGrain")` at the same time 

3- One hits the above activator code first (theres a mutex in there) and works fine and when the other hits the above code it "already exists".

Will take suggestion on how I could test this.
Not sure how the activator works here, or how its accessed ?

**Comment by potterdai** [comment]
Hi @otherview This is strange because in common scenario it should wait Activator till it finished spawning instead of sending Activator multiple spawning requests. How frequent is your message? Could you post a demo project just with the TrackerGrain so that I can have a look? Thank you very much! = )

**Comment by otherview** [comment]
I've deployed this in kubernetes and it's taking quite a beating in terms of request numbers. :)
Hard to place a small demo project though.

Additionally can't seem to replicate this locally - I have a few dockerized instances of my silos running locally.
And am using locust to do load testing. But I seem to hit io ports limits locally before any issue comes up.

I'm pasting my TrackerGrain Generated proto.
```
// TrackerGrain interfaces the services available to the TrackerGrain
type TrackerGrain interface {
	Init(id string)
	Terminate()
		
	RegisterFruitGrain(*RegisterMessage, cluster.GrainContext) (*Noop, error)
		
	RegisterCacheGrain(*RegisterMessage, cluster.GrainContext) (*Noop, error)
		
	DeregisterFruitGrain(*RegisterMessage, cluster.GrainContext) (*Noop, error)
		
	DeregisterCacheGrain(*RegisterMessage, cluster.GrainContext) (*Noop, error)
		
	BroadCastNewPieceToFruits(*PieceSummary, cluster.GrainContext) (*Noop, error)
		
	BroadCastMarkDirtyCaches(*MessageFruitID, cluster.GrainContext) (*Noop, error)
		
	BroadCastMarkDirtyFruitsAndCaches(*MessageFruitID, cluster.GrainContext) (*Noop, error)
		
}

...

// BroadCastNewPieceToFruitsWithOpts requests the execution on to the cluster
func (g *TrackerGrainGrain) BroadCastNewPieceToFruitsWithOpts(r *PieceSummary, opts *cluster.GrainCallOptions) (*Noop, error) {
	fun := func() (*Noop, error) {
			pid, statusCode := cluster.Get(g.ID, "TrackerGrain")
			if statusCode != remote.ResponseStatusCodeOK && statusCode != remote.ResponseStatusCodePROCESSNAMEALREADYEXIST {
				return nil, fmt.Errorf("get PID failed with StatusCode: %v", statusCode)
			}
			bytes, err := proto.Marshal(r)
			if err != nil {
				return nil, err
			}
			request := &cluster.GrainRequest{MethodIndex: 4, MessageData: bytes}
			response, err := rootContext.RequestFuture(pid, request, opts.Timeout).Result()
			if err != nil {
				return nil, err
			}
			switch msg := response.(type) {
			case *cluster.GrainResponse:
				result := &Noop{}
				err = proto.Unmarshal(msg.MessageData, result)
				if err != nil {
					return nil, err
				}
				return result, nil
			case *cluster.GrainErrorResponse:
				return nil, errors.New(msg.Err)
			default:
				return nil, errors.New("unknown response")
			}
		}
	
	var res *Noop
	var err error
	for i := 0; i < opts.RetryCount; i++ {
		res, err = fun()
		if err == nil || err.Error() != "future: timeout" {
			return res, err
		} else if opts.RetryAction != nil {
				opts.RetryAction(i)
		}
	}
	return nil, err
}
```

I've actually added a `&& statusCode != remote.ResponseStatusCodePROCESSNAMEALREADYEXIST`
And seems to be working fine ? *scratches head*

**Comment by potterdai** [comment]
@otherview Thank you for sharing the code. It should be fine in this case though.
Hmmm, would love to dig into those edge cases. = )
Does this happen only when there is a lot of nodes getting added into cluster?

**Comment by rogeralsing** [comment]
Closed by @otherview's fix. 

A note for everyone reading this. Grains are aimed towards high availability and edge cases do exist where processes are activated concurrently, or even dual activations on multiple nodes incase new nodes join the cluster.

This is a known issue present even in Microsoft Orleans, which pioneered the Virtual Grain concept.
