### ISSUE TITLE
[Performance] Is there any official performance comparison between ProtoActor-go and CAF?

### ISSUE THREAD

**Issue by xiaoming-qxm** [asynkron/protoactor-go#304]
ProtoActor-go claims that it's very fast when sending messages between actors.
> Ultra fast remoting, Proto Actor currently manages to pass over two million messages per second between nodes using only two actors, while still preserving message order! This is six times more the new super advanced UDP based Artery transport for Scala Akka, and 30 times faster than Akka.NET.

And there is also another popular actor framwork([CAF, C++ actor framework](https://github.com/actor-framework/actor-framework)), but I did't find any performance comparison between them. 
So my question is that is there any official performance(messages per second) comparison between ProtoActor-go and CAF?
Any answer will be appreciated. Thank in advance.

**Comment by cupen** [comment]
@xiaoming-qxm  You mean something like this?  Currently it's lacking some similar test cases for protoactor-go. Feel free to make `pr` for what you want.

![image](https://github.com/asynkron/protoactor-go/assets/1221615/947f6217-8562-42c5-b6a8-bf89d086b922)
https://inet.haw-hamburg.de/papers/chs-ccafs-14.pdf

**Comment by rogeralsing** [comment]
We also have this:
https://proto.actor/docs/performance/benchmarks/

Where we list performance for both remote and Skynet benchmarks.
Feel free to add CAF benchmark to the mix here

**Comment by cupen** [comment]
See https://github.com/asynkron/protoactor-go/issues/1128
