### ISSUE TITLE
How to respond to `RequestFuture`

### ISSUE THREAD

**Issue by Bresenham** [asynkron/protoactor-go#305]
I am Looking for a way to respond to this request:

`rootContext.RequestFuture(someActor.PID, &someMessage{})`

I tried:

`rootContext.Send(someActor.PID, &someResponse{})`

There is no `Respond`-Function, even though your GoDoc Claims that it exists [Link](https://godoc.org/github.com/AsynkronIT/protoactor-go/actor#RootContext) -> `Example (Synchronous)`

**Comment by otherview** [comment]
Hi !

> `rootContext.RequestFuture(someActor.PID, &someMessage{})`

This returns a *Future that you can `.Result()` and wait for response.

> `rootContext.Send(someActor.PID, &someResponse{})`

Does a fire-and-forget, it does not await nor return anything.

You can use `.Result()` to wait for the response from the actor.
Something like this should work for synchronous messaging:
```
response, err := rootContext.RequestFuture(pid, request, opts.Timeout).Result()
if err != nil {
  return nil, err
}
```

Best of luck ! :)

**Comment by devopsjedi** [comment]
In `Receive` method of `someActor`, you will send the response back to the caller via `(actor.Context).Sender()`.  You will get the sender's PID and send a message to it.  
Let's say this is your Receive:
```
func (s *someActor) Receive (ctx actor.Context) {
    switch msg := ctx.Message().(type) {
    case *someMessage:
      ctx.Send(ctx.Sender(), &someResponse{})
    }
}
```
An "anonymous" actor PID is created when you call `RequestFuture` and the message sent to it becomes the Result of the Future.
