### ISSUE TITLE
how about relase the protoactor-go

### ISSUE THREAD

**Issue by guagua1989** [asynkron/protoactor-go#307]
how about making a plan to release protoactor-go. Maybe that will have a goal and more people be willing to join in the  project.

**Comment by rogeralsing** [comment]
You mean a 1.0 release?

**Comment by guagua1989** [comment]
A 1.0 release is OK  if the project  is Ready. If having something will to be completed, for example, a v0.1.0 release  maybe also OK. The protoactor-go project can be more easily used by other projects with go module  if  he Having a release versions .
    Of course,some minor or major versions likes some milestone.That will be fine.
It will attract more people.

**Comment by emansom** [comment]
Project currently lacks documentation. Attracting developers requires that to be in order, imho.

**Comment by Menniti** [comment]
I would like to have any type of version if is possible! is easy to track and use here!
thank you
