### ISSUE TITLE
Misssing Documentation

### ISSUE THREAD

**Issue by benny1611** [asynkron/protoactor-go#312]
Hi guys,

I'm a computer science student and I have to make a project in Go with Proto.Actor. Because of my lack of experience (this is my first project in Go, coming from Java) and the lack of documentation on the official [website](http://proto.actor/docs/golang/) I find it very difficult to understand how one can use it. It would be nice if you could provide a better documentation. Thank you!
Edit: I also tried to send you an email but your email address doesn't seem to exist 😅 

Best regards!

PS: I have to make a "simple" binary search tree where every node is an actor

**Comment by cyphysical** [comment]
Hello, I'm working on a project using the lib and it's really frustrating that half of the links in the documentation lead nowhere. The only way to understand what the lib is to peek into the source code which is hardly straightforward
![Screen-2-25-2020_14205_PM](https://user-images.githubusercontent.com/19917423/75244571-acae2a80-57d4-11ea-83b2-e21e8286999e.png)

**Comment by cupen** [comment]
@benny1611  @alexpashkov 
https://github.com/AsynkronIT/protoactor-bootcamp

**Comment by cyphysical** [comment]
@cupen The links are for c# boot camp, how come it solves the problem with golang docs?

**Comment by rogeralsing** [comment]
Documentation for Go and C# have been merged together:

https://proto.actor/docs/hello-world/

<img width="922" alt="Skärmavbild 2020-11-01 kl  23 21 25" src="https://user-images.githubusercontent.com/647031/97816892-01c20a80-1c99-11eb-8ca5-dc52288bb224.png">
