### ISSUE TITLE
On a physical machine, the socket cannot bind 0.0.0.0

### ISSUE THREAD

**Issue by lovelly** [asynkron/protoactor-go#314]
How does the server to server send messages.
===============================
I want to be in the 'a' process
  remote.Start("0.0.0.0:8081");
a := actor.NewPID("127.0.0.1:8080", "bs");
  a.Tell{Hello{}} ;
===============================
In the 'b' process
  remote.Start("0.0.0.0:8080");
  b := actor.NewPID("127.0.0.1:8081", "as");
b.Tell{Hello{}}
===============================
Two processes cannot receive messages from each other

**Comment by cupen** [comment]
@lovelly  Here is the example.
 https://github.com/AsynkronIT/protoactor-go/blob/dev/examples/chat/ 

p.s.: could you format your text?

**Comment by lovelly** [comment]
When server uses 
```
remote.Start("0.0.0.0:8888")
actor.SpawnNamed(props, "chatserver")
```
Client  use
```
Server := actor.NewPID("127.0.0.1:8888", "chatserver")
```
The server is not correct to identify the message.
Should be in
```
func (pr *ProcessRegistryValue) Get(pid *PID) (Process, bool) {
	if pid == nil {
		return deadLetter, false
	}

	log.Println(pid.Address,"  local:  ", localAddress, " pr: ", pr.Address)
	if pid.Address != localAddress && pid.Address != pr.Address {
		for _, handler := range pr.RemoteHandlers {
			ref, ok := handler(pid)
			if ok {
				return ref, true
			}
		}
		return deadLetter, false
	}
         . . . 
```
localAddress == “nonhost”  
pr.Address == "[::]:8888"   
But  
pid.Address == "127.0.0.1:8888"  

The server thought this was a remote message and sent it out.  
So the call goes in an infinite loop.  


My server is a cloud server and can only bind 0.0.0.0. I am accessing the public network ip provided by the cloud vendor on the external network, and I will get such an error.

**Comment by cupen** [comment]
@lovelly maybe you want this?
```go
opt := remote.WithAdvertisedAddress("xx.xx.xx.xx:8888")
remote.Start("0.0.0.0:8888", opt)
```
see https://github.com/AsynkronIT/protoactor-go/blob/dev/remote/server.go#L24
