### ISSUE TITLE
eliminate golint warnings

### ISSUE THREAD

**Issue by yangdiangzb** [asynkron/protoactor-go#318]
I will eliminate some of the golint warnings in this issue. 

Here is another question.  Actually there are lots of golint warnings which are about missing comments.Since those comments are not appropriate for users to add.  Is there any plan to add comments to eliminate those warnings?

**Comment by potterdai** [comment]
@yangdiangzb Thank you very much for the PR! Indeed those comments should be added. Unfortunately it seems all members in protoactor team are currently busy with other things.
