### ISSUE TITLE
Message queues

### ISSUE THREAD

**Issue by ghost** [asynkron/protoactor-go#330]
This is more of a question - sorry.
i am used to using NATS for RPC, etc.
With this actor design, if the other server is "offline / partitioned", then if the caller makes a mutation call to the actor on the other server it just fails ?

I am researching using actors and so curious about the concepts of fault tolerance when using the Cluster with Consul.

**Comment by rogeralsing** [comment]
It depends on what kind of flavour you use.
e.g. Grains can re-spawn on other nodes if the original node it lived on is offline.

But if you use point to point. e.g. trying to send a message to a specific actor on a specific node, then yes. that message is lost, or rather forwarded to deadletter queue on the local node
