### ISSUE TITLE
Is there any official timeline or plan for releasing protoacotor-go?

### ISSUE THREAD

**Issue by yangdiangzb** [asynkron/protoactor-go#343]
Currently, protoactor-go is still in beta development. Is there any official timeline or plan to release protractor-go? @PotterDai

**Comment by dennis-tra** [comment]
I'd be interested in a timeline or next milestones as well. 

I would also offer to help out with things.

_PS: The same discussion was also brought up in #307_

**Comment by rogeralsing** [comment]
There are currently no major API changes going on so code-wise we are good to go IMO. 
There are bug fixes etc coming in, but no major redesigns of any module.

The main issue is lack of documentation, so getting some help on this aspect would be great.

Maybe a good start would be to first list what areas are in need of better documentation, what is lacking etc.

And possibly even set up some form of funding to support writing docs.
Not to make anyone rich but to at least make that effort a bit more attractive for all the contributors

Thoughts?

**Comment by yangdiangzb** [comment]
@rogeralsing Sounds great! Looking forward to the plans of documentation and happy to help! 

However, a little concern about the quality of documentation if those documentations are not written by your teammates.

**Comment by bryanpkc** [comment]
@yangdiangzb That's what pull requests are for. We can iterate on the documentation until the content is high enough quality to merge.

**Comment by Ghvstcode** [comment]
Related to #307
