### ISSUE TITLE
Way forward

### ISSUE THREAD

**Issue by rogeralsing** [asynkron/protoactor-go#348]
As the Go version of Proto.Actor has the most traction, let's keep the discussion here.

How can we push the final bits in place to make this go v1 ?

What if we set up a Patreon. https://www.patreon.com/user?u=22991983
I'm not sure how likely it is that anyone actually donates to this kind of efforts.

But I'm thinking it could be used to motivate the documentation effort.
Be it external or internal devs on the project.

eg. X $ from the funds per merged page of documentation to the author.
Maybe that is just naive on my part, but coding is fun, documenting is not.
And everyone here is doing this on a spare time basis.

Is it even worth considering/evaluating?

Are there any other examples, use cases etc. that needs to be added?

**Comment by dennis-tra** [comment]
> How can we push the final bits in place to make this go v1 ?

Here is my quick brainstorm:

#### Documentation:
I think this has the highest priority. I couldn't find the source for the [proto.actor](http://proto.actor/) website. Is it open for contributions?

In my opinion the first task would be to identify what's missing and what needs an update. Maybe another issue where we can build a list? Or here?

#### Test coverage
I think core packages (like the `remote` package) could benefit from an increased coverage for a stable v1 and subsequent v1.x.x releases. I'm not a friend of a policy that says at least XX % lines of code need to be tested, so it's hard to say when it suffices. I believe because of the asynchronous nature of this project it is really hard to test the functionality thoroughly though...

_Btw: The coverage badge says `unknown` at the moment._

#### Funding
I don't have any experience with OSS funding and I also don't know how likely it is for anyone to donate. But if there is no monetisation channel in place those few who would want to donate can't. So I like the idea of having Patreon in place.

**Comment by rogeralsing** [comment]
The live site is generated from the content in this repo:
https://github.com/AsynkronIT/gam-web

"gam" predates Proto.Actor and was "Go Actor Model" in the very beginning :-)

**Comment by dennis-tra** [comment]
Ah okay, I didn't look into the `gam-web` repo :)

What do you think of a GitHub project board that lists all issues relevant for a 1.0 release based on a tag like `v1.0`? Based on the discussion here I could create a first batch of issues and everyone who wants could throw in their own ones. If an issue is relevant or not can be discussed on that particular ticket.

With that being said, I just had a look through the different pages and here is what I noticed:

Missing pages on the top level [http://proto.actor/docs/](http://proto.actor/docs/):

1. Remote - Dead link
2. Persistance - New
3. Plugins - New
4. EventStream - New
5. Mailbox + Dispatchers - New
6. Router - Dead link

All the other pages should probably be checked for working links and up-to-dateness.

Most of the pages under http://proto.actor/docs/golang/ are empty. Except:

1. EventStream ([Link](http://proto.actor/docs/golang/eventstream))
2. Dispatchers ([Link](http://proto.actor/docs/golang/dispatchers))
3. Mailbox ([Link](http://proto.actor/docs/golang/mailboxes))
4. Deadletters ([Link](http://proto.actor/docs/golang/deadletter))
5. GAM Cluster ([Link](http://proto.actor/docs/golang/cluster))

In this case I have a radical proposal to remove the `Documentation` -> `Go` part entirely from the website and solely rely on the GoDocs that can already be accessed via `Documentation` -> `Go API docs`.

The populated pages above could be moved to/merged into the top level http://proto.actor/docs/ docs. I suppose the `EventStream`, `Dispatchers` and `Deadletters` are concepts applicable to all proto.actor implementations. 

All subsections under http://proto.actor/docs/golang/ that are empty at the moment could be documented in code with working example snippets.

Other thoughts

- it would be cool to have a language selector for code examples where applicable. Similar to Firebase - [example](https://firebase.google.com/docs/firestore/quickstart#set_up_your_development_environment).
- I think a general Getting started section would be great as well. But I don’t know what should go in there…
- Maybe some of the examples in the `examples` package could be transformed into tutorials where one could select the language of choice.

These are just my thoughts and probably not everything is necessary for a 1.0 release. So let me know what you think ;)

**Comment by linkerlin** [comment]
A mailbox with Redis list as backend is a good choice for cross-language ops.
PHP/Python/Ruby etc. can read/write a Redis list to talk with proto.actors.

**Comment by cupen** [comment]
@linkerlin `cross-language` is good idea, it's done by cross-platform serializtion library `protobuf`.

**Comment by linkerlin** [comment]
> @linkerlin `cross-language` is good idea, it's done by cross-platform serializtion library `protobuf`.

If I have a PHP-based web-site, and I want to extend it with Golang-based protoactors, there is no easy way to do it .
But if we have a Redis list as a middleman, we can do it fast and clean.

**Comment by cupen** [comment]
@linkerlin Hi, sorry for delay.
It seems like you want a `mailbox-redis` implements. It's a good idea, but it's not necessarily for protoactor v1.0. You can issue a new topic and refer it here or there.

BTW, I agree with @dennis-tra .
For a v1.0 project,  the documents and stability is important.
For a `actor framework`,  try to do what `actor framework` should to do would be enough,  some non-core features (e.g. mailbox-redis mailbox-kafka) could be implemented by other projects.

**Comment by linkerlin** [comment]
@cupen I have a new idea of webassebly with proto.actor-go.
If we build a wrap for proto.actor-go which make it can run with chrome/safari and directly talk to a actor-cloud, maybe SPA can use it .

**Comment by ghost** [comment]
I've just started looking at this project.  It has a lot that I'd like to use, but I'm struck by the documentation issues - missing docs, or docs that do not match the current api (e.g. proto.actor website has examples with pid.Tell vs. context.Send).  I'd like to help with this : is there a doc effort underway that I could help contribute to, or is it something that I can best help with on an ad-hoc basis?

**Comment by Valentin-Miroshnichenko** [comment]
Hi Jim3Things. I started to wrote documentation to our project. But now there are two problems it's documentation for C# and Python and currently it on Russian language(i haven't started translate to english yet). If you want, I can public it on githab and you can using google translate to read it.

**Comment by ghost** [comment]
It can't hurt, thanks.
