### ISSUE TITLE
Question, no pid on second example?

### ISSUE THREAD

**Issue by kokizzu** [asynkron/protoactor-go#353]
Why the 2nd example on `README.md` `Send` directly `Hello` without `pid`? while the first example uses `pid` `context.Send(pid,Hello{...`
```
func main() {
    context := actor.EmptyRootContext
    props := actor.PropsFromProducer(NewSetBehaviorActor)
    pid, err := context.Spawn(props)
    if err != nil {
        panic(err)
    }
    context.Send(Hello{Who: "Roger"})
    context.Send(Hello{Who: "Roger"})
    console.ReadLine()
}
```

**Comment by emilingerslev** [comment]
This seems a bit like half the old and half the new syntax, and I'm pretty sure it just need to be corrected.
The old syntax allowed `pid.Send(msg)`

**Comment by emilingerslev** [comment]
Just added a PR to fix it 😊👆

**Comment by potterdai** [comment]
@emilingerslev Thank you for the PR = ) Just got it merged!

**Comment by emilingerslev** [comment]
@PotterDai it was nothing. Really 😉
