### ISSUE TITLE
how to access protoactor cluster from external http service?

### ISSUE THREAD

**Issue by moonspirit** [asynkron/protoactor-go#365]
I have a http service named lobby, and a protoactor cluster accounts

lobby should be able to request to accounts cluster

Seems lobby should watch consul and do not Register its self as a Member? But the cluster.Start will automatically Register itsself.

Is there any examples to do it?

Thanks very much in adavance!

**Comment by potterdai** [comment]
@moonspirit You should set up a client Node, who has the access to the cluster, then use it to connect with user devices, either using websocket or RESTful as you wish = )

**Comment by moonspirit** [comment]
@PotterDai  Thanks! Do you known any examples demostrate how to setup a cluster client Node?

**Comment by linkerlin** [comment]
@moonspirit Using a redis-server with redis-lists as  queues, then talk to actors with messages in the queues.

**Comment by moonspirit** [comment]
@linkerlin This seems like a MQ solution, what i want is maybe a http service that hides the internal details of actor system and exposes only the stateless service. To implement that, the http service need to know how to route messages to its destitination actors.

**Comment by otherview** [comment]
@moonspirit does https://github.com/AsynkronIT/protoactor-go/tree/dev/_examples/cluster-broadcast help ?

It doesn't care "where" the actor lives, you just call is by its Id and issue a request to it.

The Http service is just another layer, and somewhere in that layer, it calls the cluster services.
For example here:
https://github.com/AsynkronIT/protoactor-go/blob/b225d28383f2318e0513dfabd22a3037f9043ffd/_examples/cluster-broadcast/node1/main.go#L69-L74

**Comment by cupen** [comment]
@moonspirit  Hello! You need register it self as a member by `cluster.Start(...)`, then you can access the cluster in your http request session.
BTW: Maybe this could be modified in the future. Here is the dotnet version's issue https://github.com/AsynkronIT/protoactor-dotnet/issues/552 .

**Comment by cupen** [comment]
@moonspirit  
### Register client node that running as a member without any kinds actor.
```go
func startClientNode(addr string) {
	cp, err := consul.New()
	if err != nil {
		panic(err)
	}
	cluster.Start("mycluster", addr, cp)
}

```

### Register server node.
``` go
func startServerNode(addr string) {
	timeout := 10 * time.Second
	remote.Register("Calculator", actor.PropsFromProducer(func() actor.Actor {
		return &shared.CalculatorActor{
			Timeout: &timeout,
		}
	}))

	cp, err := consul.New()
	if err != nil {
		panic(err)
	}
	cluster.Start("mycluster", addr, cp)
}
```
Here is a executable example https://github.com/cupen/protoactor-go/tree/cluster-provider-etcd/_examples/cluster-restartgracefully
