### ISSUE TITLE
Question about distribution of actors in protoactor cluster 

### ISSUE THREAD

**Issue by moonspirit** [asynkron/protoactor-go#366]
Looked into soucecode and found that protoactor uses Rendezvous (kind of consistent hash algorithm) to locate the destination Node by actor name.

Since adding/removing nodes in Rendezvous results actor distribute being rebalanced(maybe just 1/N actors will be affected), and those actors get rebalance to a new Node.

So if we add new Node into the cluster, or one Node get isolated from the cluster and rejoin back later, there will be actors in Two Nodes with same actor name and result in data consistency issues?

**Comment by potterdai** [comment]
@moonspirit Hi, yes ProtoActor is using Rendezvous to locate **Partition** (it’s a registry of actors, like an address book). The actors themselves are distributed randomly across all Nodes. The good thing about this strategy is that, when a Node left/join the cluster, the rebalance only happens between **Partitions**, actors themself will not be killed or reinstantiated, thus reducing the overhaul of rebalancing.
