### ISSUE TITLE
Are there any benchmark numbers available?

### ISSUE THREAD

**Issue by zhiqiangxu** [asynkron/protoactor-go#381]
E.g, `protoactor-go` vs `chan`, how much faster can it be by using `protoactor-go`?

**Comment by stunkki** [comment]
You can use both. Hope this helps:

https://gist.github.com/kachayev/21e7fe149bc5ae0bd878

Here are some benchmarks compared to other actor frameworks:

https://github.com/alexvaluyskiy/ActorBenchmarks/blob/master/README.md
