### ISSUE TITLE
panic: protobuf tag not enough fields in PID.p

### ISSUE THREAD

**Issue by liov** [asynkron/protoactor-go#382]
the README example of network
protoc 3.10
gogoproto1.3

panic: protobuf tag not enough fields in PID.p: 

```
goroutine 12 [running]:
github.com/gogo/protobuf/proto.(*unmarshalInfo).computeUnmarshalInfo(0xc000202460)
```

**Comment by liov** [comment]
The strange thing is that chat example works fine

**Comment by cupen** [comment]
Could you provide the full trace log?

**Comment by cupen** [comment]
@liov  I find a example similar to the code in README. It works fine.
https://github.com/AsynkronIT/protoactor-go/tree/dev/examples/remoteactivate
