### ISSUE TITLE
[Error] An unexpected error when running tests.

### ISSUE THREAD

**Issue by ChaokunChang** [asynkron/protoactor-go#383]
I am running the test of protoactor-go following the README instruction, and met an error in timer_test.go:43.

### Environment
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOENV="/home/ubuntu/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ubuntu/go/src/github.com/AsynkronIT/protoactor-go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build467598037=/tmp/go-build -gno-record-gcc-switches"

### Reproduce
go get github.com/AsynkronIT/protoactor-go/...
cd $GOPATH/src/github.com/AsynkronIT/protoactor-go
go get ./...
make
go test -count=1 `go list ./... | grep -v consul` | grep -v 'no test files'

### Error Message 
ok      github.com/AsynkronIT/protoactor-go/actor       0.213s
ok      github.com/AsynkronIT/protoactor-go/actor/middleware/opentracing        0.054s [no tests to run]
ok      github.com/AsynkronIT/protoactor-go/actor/middleware/propagator 0.005s
ok      github.com/AsynkronIT/protoactor-go/cluster     0.050s
ok      github.com/AsynkronIT/protoactor-go/cluster/weighted    0.018s [no tests to run]
ok      github.com/AsynkronIT/protoactor-go/eventstream 0.028s
ok      github.com/AsynkronIT/protoactor-go/internal/queue/goring       1.818s
ok      github.com/AsynkronIT/protoactor-go/internal/queue/mpsc 1.405s
ok      github.com/AsynkronIT/protoactor-go/log 0.028s
ok      github.com/AsynkronIT/protoactor-go/mailbox     3.162s
ok      github.com/AsynkronIT/protoactor-go/persistence 0.023s
ok      github.com/AsynkronIT/protoactor-go/plugin      1.213s
ok      github.com/AsynkronIT/protoactor-go/remote      0.124s
ok      github.com/AsynkronIT/protoactor-go/router      2.138s
--- FAIL: TestNewTimerScheduler (0.05s)
    --- FAIL: TestNewTimerScheduler/does (0.04s)
        --- FAIL: TestNewTimerScheduler/does/send_repeatedly (0.01s)
            timer_test.go:43: 
                        Error Trace:    timer_test.go:43
                                                                timer_test.go:64
                        Error:          failed to receive message 3 != 5
                        Test:           TestNewTimerScheduler/does/send_repeatedly
        --- FAIL: TestNewTimerScheduler/does/request_repeatedly (0.02s)
            timer_test.go:43: 
                        Error Trace:    timer_test.go:43
                                                                timer_test.go:79
                        Error:          failed to receive message 0 != 5
                        Test:           TestNewTimerScheduler/does/request_repeatedly
            timer_test.go:43: 
                        Error Trace:    timer_test.go:43
                                                                timer_test.go:79
                        Error:          failed to receive message 1 != 5
                        Test:           TestNewTimerScheduler/does/request_repeatedly
            timer_test.go:43: 
                        Error Trace:    timer_test.go:43
                                                                timer_test.go:79
                        Error:          failed to receive message 2 != 5
                        Test:           TestNewTimerScheduler/does/request_repeatedly
            timer_test.go:48: 
                        Error Trace:    timer_test.go:48
                                                                timer_test.go:79
                        Error:          Not equal: 
                                        expected: 5
                                        actual  : 3
                        Test:           TestNewTimerScheduler/does/request_repeatedly
FAIL
FAIL    github.com/AsynkronIT/protoactor-go/scheduler   0.071s
ok      github.com/AsynkronIT/protoactor-go/stream      0.035s
FAIL

### Question
What makes me confused is that: This error doesn't occur every time, sometimes I will get this error, sometimes totally ok. Is this a normal phenomenon?

**Comment by SunflowerAries** [comment]
I also met this problem. Can someone help us?

**Comment by ccamel** [comment]
@ChaokunChang  The test that fails is written with a timeout, so if your build server is running under heavy load the timeout may not be long enough...

```go
  ...
  case <-time.After(3 * time.Millisecond):
    if got != exp {
      assert.Fail(t, "failed to receive message")
    }
  }
```

**Comment by ChaokunChang** [comment]
Got it. Thanks a lot.
