### ISSUE TITLE
mailbox.(*defaultMailbox).processMessages use 100% cpu

### ISSUE THREAD

**Issue by coverthesea** [asynkron/protoactor-go#388]
github.com/AsynkronIT/protoactor-go/mailbox.(*defaultMailbox).processMessages,use my cpu 100%
my server is centos7
I use pprof check it
    4480ms 39.89% 39.89%    11220ms 99.91%  github.com/AsynkronIT/protoactor-go/mailbox.(*defaultMailbox).processMessages
    2180ms 19.41% 59.31%     3180ms 28.32%  runtime.deferreturn
    1450ms 12.91% 72.22%     6740ms 60.02%  github.com/AsynkronIT/protoactor-go/mailbox.(*defaultMailbox).run

**Comment by cupen** [comment]
@coverthesea Could you provide a example code that reproduce it?
