### ISSUE TITLE
Could an actor has both local address and remote address?

### ISSUE THREAD

**Issue by cupen** [asynkron/protoactor-go#389]
For example:  
nodeA and nodeB running on different hosts.
nodeB has some childrens.
could them works like this?
```
nodeA  <-- remote --> nodeB
nodeA  <-- remote --> nodeB.childrens
nodeB  <-- local -->  nodeB.childrens
```

**Comment by otherview** [comment]
It kinda works like that 😃 

When the receiving host requests a grain it uses a DHT to calculate where the node is. In this case, it will call itself.

Off the top of my head, I'm not sure if the message it sends goes through a "remote call" to itself or if it directly puts the message in the local actor mailbox though 🤔 
Was that what you were trying to figure out ?

**Comment by cupen** [comment]
@otherview  Yes, it's what I'm figure out. Thank you for your reply.  :smiley:

**Comment by cupen** [comment]
It's not a problem,  just a question.  I will close it off now.
