### ISSUE TITLE
log: maybe we need a logging library?

### ISSUE THREAD

**Issue by cupen** [asynkron/protoactor-go#396]
Here is some logs from my fork of  `protoactor-go`.
It looks not very neat even it's using `log.Printf` that same as `cluster/consul`.
```
Started EndpointManager 
Starting Proto.Actor server address="127.0.0.1:8080" 
Starting Proto.Actor cluster address="127.0.0.1:8080" 
Started Activator 
Started kind="Tracker" id="partition-Tracker" 
Started kind="Calculator" id="partition-Calculator" 
Member joined kind="Calculator" name="127.0.0.1:8080" 
Member joined kind="Tracker" name="127.0.0.1:8080" 

Boot other nodes and press Enter
2020-09-09 17:11:14.536210 I | [CLUSTER] [ETCD] Skip self: /protoactor/mycluster/mycluster@127.0.0.1:8080.
2020-09-09 17:11:14.536223 I | [CLUSTER] [ETCD] ClusterTopologyEvent: 1
2020-09-09 17:11:14.536249 I | [CLUSTER] [ETCD]    &{MemberID:mycluster@127.0.0.1:8080 Host:127.0.0.1 Port:8080 Kinds:[Calculator Tracker] Alive:true StatusValue:<nil>}
```
Maybe we should just use  "github.com/AsynkronIT/protoactor-go/log"? 
or maybe we should use a mature third-party logging library?
https://github.com/avelino/awesome-go#logging

BTW: zaplog is nice, I recommend it.

**Comment by nightwolfz** [comment]
+1

I'm using zaplog myself. Especially the SugaredLogger is very helpful during development since you can see where the messages originated from (file and line number).

**Comment by cupen** [comment]
> +1
> 
> I'm using zaplog myself. Especially the SugaredLogger is very helpful during development since you can see where the messages originated from (file and line number).

En...  I have changed my mind. After a little fix, the `protoactor-go/log` works fine now.  I can port the feature(file and line number) you loved for it.  Just one problem when use it with `os.Exit`. 
e.g.:
```go
plog.Error("Surprise! You can't see me.") // it just send string to a channel.
os.Exit(0)
```
Any suggestions?
