### ISSUE TITLE
Way to send periodical messages to actors without tracking

### ISSUE THREAD

**Issue by AlfredDobradi** [asynkron/protoactor-go#398]
I've been trying to find a way for a while now but couldn't make it work, I'd like to have a monitor actor that is able to request the available members and send them a message periodically (signalling to persist their data, ping them for availability, etc).

Initially I used the tracking grain method I saw in the `cluster-broadcast` example and it worked fine, but I'm curious if there's a way to do this without having to have the actors register themselves.

When I call `cluster.Get(name, kind)` I get the PID I can use to send the messages but using `cluster.GetMemberPIDs(kind)` the PIDs I get as a result can't be used for sending messages, they end up as dead letters.

This is the piece of code I'm using that ends up sending dead letters:
```
	pids := cluster.GetMemberPIDs("Member")
	spew.Dump(pids.Values())
        // ([]actor.PID) (len=2 cap=2) {
        //     (actor.PID) 127.0.0.1:8080/Member,
        //     (actor.PID) 127.0.0.1:8081/Member
        // }

	pids.ForEach(func(i int, a actor.PID) {
		bytes, err := proto.Marshal(&DummyRequest{})
		if err != nil {
			return
		}
		request := &cluster.GrainRequest{MethodIndex: 0, MessageData: bytes}
		response, err := rootContext.RequestFuture(&a, request, 60*time.Second).Result()
		if err != nil {
			log.Printf("request error: %v", err)
		}
		switch msg := response.(type) {
		case *cluster.GrainResponse:
			result := &DummyResponse{}
			err = proto.Unmarshal(msg.MessageData, result)
			if err != nil {
				log.Printf("response error: %v", err)
			}

			log.Printf("success: %v", result)
		case *cluster.GrainErrorResponse:
			log.Printf("error: %v", msg.Err)
		default:
			log.Println("unknown response")
		}
	})
```

I use the same code to send a request when using `cluster.Get(name, kind)` to send the message, in that case the PID is `(actor.PID) 127.0.0.1:8080/Remote$1111111100000001` and the request is successful.

My question is, is this even possible and/or a good idea even, and if it's something that can work, what am I doing wrong?

**Comment by nightwolfz** [comment]
@AlfredDobradi 

Probably not the best way (I'm still learning) but what I did was create a "watcher" actor singleton that listens to the eventstream:

```
func (s *watcherActor) Subscribe() {
	/// Subscribe to topology change events
	/// Detect when servers go up and down
	eventstream.Subscribe(func(evt interface{}) {
		switch msg := evt.(type) {
		case cluster.ClusterTopologyEvent:
			for _, member := range msg {
				if member.Alive {
					s.SendSelf(&rpc.ClientOnline{Kinds: member.Kinds, Address: member.Address()})
				} else {
					s.SendSelf(&rpc.ClientOffline{Kinds: member.Kinds, Address: member.Address()})
				}
			}
		}
	})
}

func (s *watcherActor) Receive(c actor.Context) {
	switch msg := c.Message().(type) {
	case *rpc.ClientOnline:
          //....
        case *rpc.ClientOffline:
           //....
        }
}
```

Then inside the message switch, I listen to rpc.ClientOnline/rpc.ClientOffline and update a map of actor addresses.

I'm not using grains though, so this might not work for you...
