### ISSUE TITLE
Messages are lost when doing load testing on simple actor

### ISSUE THREAD

**Issue by sujit-baniya** [asynkron/protoactor-go#400]
I created following code for testing and seems messages are lost (maybe due to race)

```go
package main

import (
	"fmt"

	console "github.com/AsynkronIT/goconsole"
	"github.com/AsynkronIT/protoactor-go/actor"
	"github.com/AsynkronIT/protoactor-go/router"
)

type workItem struct{ i int }
var counter = 0
const maxConcurrency = 5

func doWork(ctx actor.Context) {
	if _, ok := ctx.Message().(*workItem); ok {
		counter++
	}
}

func main() {
	rootContext := actor.EmptyRootContext
	pid := rootContext.Spawn(router.NewRoundRobinPool(maxConcurrency).WithFunc(doWork))
	for i := 0; i < 1000000; i++ {
		rootContext.Send(pid, &workItem{i})
	}
	fmt.Println(counter)
	console.ReadLine()
}
```
Some time I get `962126` and some time `966524` but no exact 1000000.

What should be done to fix it?

**Comment by dennis-tra** [comment]
Hi @itsursujit ,

I suspect this is indeed a race here. 

2 Points:

1. When you call `Send` the messages are only put into the Mailbox of your actors and not yet processed - aka the counter is not incremented at this point. So when you leave the loop to print the `counter` value it won't reflect all processed messages and therefore you'll see a lower count as expected. For the sake of my argument I presume if you just put a `time.Sleep(time.Second)` after your loop you wouldn't run into this problem. However this shouldn't be done in any serious environment but some kind of synchronisation would be needed.

2. Concurrently updating the counter across five actors is also a race condition and can lead to a mismatch of the expected count to the actual count value. Some kind of synchronisation is also needed here.

**Comment by sujit-baniya** [comment]
@dennis-tra Indeed using Sleep and `atomic.AddInt64(&counter,1)` does the trick. How can we make sure all messages are processed without using Sleep?

```go
package main

import (
	"fmt"
	"sync/atomic"
	"time"

	console "github.com/AsynkronIT/goconsole"
	"github.com/AsynkronIT/protoactor-go/actor"
	"github.com/AsynkronIT/protoactor-go/router"
)

type workItem struct{ i int }
var counter int64 = 0
const maxConcurrency = 5

func doWork(ctx actor.Context) {
	if _, ok := ctx.Message().(*workItem); ok {
		atomic.AddInt64(&counter, 1)
	}
}

func main() {
	rootContext := actor.EmptyRootContext
	pid := rootContext.Spawn(router.NewRoundRobinPool(maxConcurrency).WithFunc(doWork))
	for i := 0; i < 1000000; i++ {
		rootContext.Send(pid, &workItem{i})
	}
	time.Sleep(time.Second)
	fmt.Println(counter)
	console.ReadLine()
}
```
This gives me the exact value.

Any code snippet you could suggest?

**Comment by dennis-tra** [comment]
Great to hear it's working as expected now.

I would suggest using a WaitGroup:

```go
package main

import (
	"fmt"
	"sync/atomic"
	"time"

	console "github.com/AsynkronIT/goconsole"
	"github.com/AsynkronIT/protoactor-go/actor"
	"github.com/AsynkronIT/protoactor-go/router"
)

type workItem struct{ i int }
var counter int64 = 0
var wg sync.WaitGroup
const maxConcurrency = 5

func doWork(ctx actor.Context) {
	if _, ok := ctx.Message().(*workItem); ok {
                wg.Done()
		atomic.AddInt64(&counter, 1)
	}
}

func main() {
	rootContext := actor.EmptyRootContext
	pid := rootContext.Spawn(router.NewRoundRobinPool(maxConcurrency).WithFunc(doWork))
	for i := 0; i < 1000000; i++ {
                 wg.Add(1)
		rootContext.Send(pid, &workItem{i})
	}
	wg.Wait()
	fmt.Println(counter)
	console.ReadLine()
}
```

I haven't run this code so there may be syntax errors or similar.

**Comment by sujit-baniya** [comment]
@dennis-tra it's working great. Thanks
