### ISSUE TITLE
Is it ok that log.Fatal in actor? It will cause os/process exit.

### ISSUE THREAD

**Issue by cupen** [asynkron/protoactor-go#405]
I found this in grain code generator.
https://github.com/AsynkronIT/protoactor-go/blob/b225d28383f2318e0513dfabd22a3037f9043ffd/protobuf/protoc-gen-gograin/template.go#L157-L162

The function body of `log.Fatalf`, it will kill all of the actors.
```go
// Fatalf is equivalent to Printf() followed by a call to os.Exit(1).
func Fatalf(format string, v ...interface{}) {
	std.Output(2, fmt.Sprintf(format, v...))
	os.Exit(1)
}
```

**Comment by rogeralsing** [comment]
related to https://github.com/AsynkronIT/protoactor-go/issues/396
