### ISSUE TITLE
Port ClusterInit to Go

### ISSUE THREAD

**Issue by rogeralsing** [asynkron/protoactor-go#409]
https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Cluster/Partition/PartitionPlacementActor.cs#L172

This is basically a small message with 3 fields, Cluster (the actual cluster instance), Identity and Kind.
This is useful for virtual actors to know their own name in the cluster.
Especially useful when combined with persistence, so the actor knows what state to load

**Comment by cupen** [comment]
How about get cluster instance and grainID from `cluster.GrainContext` ?

**Comment by cupen** [comment]
Or how about  `context.SpawnWithArgs` ?

**Comment by LostLaser** [comment]
I would like to pick this up. I am a bit confused by the provided link though. I would think the fix for this issue would just be adding a new type to a proto file?

**Comment by cupen** [comment]
It's done.
https://github.com/AsynkronIT/protoactor-go/blob/df2fc305778c5875a88880f2eb376a4298622f73/cluster/partition_placement_actor.go#L168-L177
