### ISSUE TITLE
Port RequestAsyncStrategy to Go

### ISSUE THREAD

**Issue by rogeralsing** [asynkron/protoactor-go#410]
https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Cluster/RequestAsyncStrategy.cs

RequestAsyncStrategy is a wrapper around cluster.Get to get a PID to a cluster actor, and then do a request to this actor.
The request async strategy encapsulates the logic around how to do. retries if the remote actor does not respond.

**Comment by cupen** [comment]
It‘s done.
https://github.com/AsynkronIT/protoactor-go/blob/dev/cluster/cluster.go#L230

**Comment by rogeralsing** [comment]
Continued in new issue
