### ISSUE TITLE
Copy Proto.Actor .NET proto files to Go

### ISSUE THREAD

**Issue by rogeralsing** [asynkron/protoactor-go#416]
In the effort to align the APIs, we also need to copy over the proto files from .NET to Go.

**Comment by cupen** [comment]
It's done.
https://github.com/AsynkronIT/protoactor-go/blob/dev/cluster/protos.proto

**Comment by rogeralsing** [comment]
ongoing efforts here https://github.com/AsynkronIT/protoactor-go/pull/478

Actor, Remote and Cluster protos are synced up there (again)
