### ISSUE TITLE
Support opentelemetry

### ISSUE THREAD

**Issue by acroca** [asynkron/protoactor-go#466]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I use opentelemetry in my project and I think it'd be better if protoactor had a middleware built in.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by rogeralsing** [comment]
Adding this to the roadmap

**Comment by rogeralsing** [comment]
Closing as duplicate of #477
