### ISSUE TITLE
Can a version be released?

### ISSUE THREAD

**Issue by yuansudong** [asynkron/protoactor-go#469]
We expect to have a version, which is used in the project now and will not be supported after a period of time. Now we are ruined by this project

**Comment by cupen** [comment]
Related to #438 #307 
But... what?  How did you ruined by this project? :cold_sweat: It sounds pretty terrible.

**Comment by gegeshao** [comment]
When will the version be upgraded to 1.0

**Comment by rogeralsing** [comment]
tagged the 0.1.0 version a few days ago.
We are working on a major API upgrade, already in dev, but more features are coming in.
