### ISSUE TITLE
Metrics plugin

### ISSUE THREAD

**Issue by rogeralsing** [asynkron/protoactor-go#477]
Port the metrics plugin from .NET to Go.
We need to find a stable abstraction for metrics that we can use to for this

**Comment by rogeralsing** [comment]
Open Telemetry?
https://github.com/open-telemetry/opentelemetry-go

**Comment by rogeralsing** [comment]
Very much related to https://github.com/AsynkronIT/protoactor-go/issues/466

**Comment by rogeralsing** [comment]
https://github.com/AsynkronIT/protoactor-dotnet/tree/dev/src/Proto.Actor/Metrics

**Comment by DamnWidget** [comment]
I am a bit confused about the wording used in this issue. Shall the OpenTelemetry support be implemented as an implementation of the `plugin.plugin` interface (thus using MiddleWare) or like in the DotNet version (directly filling the instruments in the specific relevant code)?
