### ISSUE TITLE
Port PartitionIdentityActor

### ISSUE THREAD

**Issue by rogeralsing** [asynkron/protoactor-go#482]
Ongoing effort for IdentityLookup here:
https://github.com/AsynkronIT/protoactor-go/pull/478

https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Cluster/Partition/PartitionIdentityActor.cs

**Comment by avinashdhinwa** [comment]
I would like to work on this one

**Comment by rogeralsing** [comment]
👍🏻 Great to hear!

**Comment by rogeralsing** [comment]
Make sure to use the identity_lookup branch for both issues

**Comment by rogeralsing** [comment]
Empty boilerplate for Go
https://github.com/AsynkronIT/protoactor-go/blob/identity_lookup/cluster/partition-identity/identity_actor.go

**Comment by rogeralsing** [comment]
Done
