### ISSUE TITLE
Port KubernetesClusterProvider

### ISSUE THREAD

**Issue by rogeralsing** [asynkron/protoactor-go#486]
Ongoing effort for IdentityLookup here:
#478

https://github.com/AsynkronIT/protoactor-dotnet/tree/dev/src/Proto.Cluster.Kubernetes

**Comment by avinashdhinwa** [comment]
I can work on this, have tried something similar to this already (that is wip though)

**Comment by avinashdhinwa** [comment]
@rogeralsing What is the kind of architecture here, are all the processes in same namespace or can they be in different namespaces too?

Also, are there some kind of assumptions that how we can know the pod metadata of this process?
(for eg. we might be injecting some kind of environment variables using downward api)

**Comment by rogeralsing** [comment]
These are the relevant bits for registering new metadata in the .NET provider:

https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Cluster.Kubernetes/KubernetesProvider.cs#L86

https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Cluster.Kubernetes/KubernetesProvider.cs#L103

https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Cluster.Kubernetes/KubernetesProvider.cs#L124

But yes, same namespace for all processes
Metadata is registered as labels, with label prefixes:
https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/src/Proto.Cluster.Kubernetes/ProtoLabels.cs

**Comment by DamnWidget** [comment]
Hey guys, I am working on this, slowly, as part of a growing program in the company I work for (what means I can only dedicate a few hours to it each two weeks). Anyway, I think I am progressing well, already have the member registration (labels patching etc) in place.

Regards.
