### ISSUE TITLE
Proto Grain generator generates code for imported files

### ISSUE THREAD

**Issue by rogeralsing** [asynkron/protoactor-go#500]
The Protoc code generator we have for grains, incorrectly generates code for imported files also.
This means that if you have a RPC service definition in a.proto, and import b.proto, which does not have any RPC service definition. there will still be a `b` artifact generated. but with no grains in it.

**Comment by cupen** [comment]
You mean `protoc -I=.  --gograinv2_out=.  ./a.proto`? 
or  `protoc -I=.  --gograinv2_out=.  ./*.proto`?

**Comment by cupen** [comment]
Oh, I see it.
