### ISSUE TITLE
Notes for the design of cluster

### ISSUE THREAD

**Issue by cupen** [asynkron/protoactor-go#511]
## pros:
1. It's really nice to find the address of an actor ( PID ) by Kind and ID, no matter how many cluster members. 
    More specifically,, no matter how many processes running on how many machines.
2. `grain codegen` is good idea. It made a well-understand request-reply pattern which is enough to cover 95% of my need.

## cons (#435):
1. Too many IdentityHandoverRequests when cluster members scaling up or down, its time complexity is O(n^2 * (m/n)).
    n = How many cluster members
    m = How many grains in all of cluster members
    m/n = Average of how many grains in a cluster member
2.  The `ActivationRequest` will spend serveral `RTT`, beacuse The `PartitionIdentiyActor` will forward it serveral times in some worse cases. And also there is a worsest case (a->b->a->b) may causing high cpu usage.
3. The `ActivationTerminated`, its problem as above.

btw:  Sorry for my poor English.

**Comment by rogeralsing** [comment]
All of this is handled by the IdentityLookup interface introduced in .NET, half finished port to Go.
Basically it allows the entire process of handovers to be substituted with e.g. a database lookup, say Redis or Mongo.

Doing so comes with a bit of overhead, but as the result is then cached, the overhead is pretty minimal in terms of application impact.

More info here: https://proto.actor/docs/cluster/#cluster-architecture-overview


But yes, totally agree, this needs to be fixed for the Go version

**Comment by cupen** [comment]
Yeah, I know it's half work  :smiley: .  I just note it for some guys who ask me "Is cluster ready for production?" or "How you doing with protoactor-go?". 
btw: I'll port `IdentityLookup` to Go next month,  too busy these months.

**Comment by Tochemey** [comment]
> Yeah, I know it's half work 😃 . I just note it for some guys who ask me "Is cluster ready for production?" or "How you doing with protoactor-go?". btw: I'll port `IdentityLookup` to Go next month, too busy these months.

@cupen I hope you are not referring to me 😁

**Comment by cupen** [comment]
@Tochemey  Oh, **of course not** only :smile:

**Comment by rogeralsing** [comment]
Outdated due to porting .NET version
