### ISSUE TITLE
Where is the copyright?

### ISSUE THREAD

**Issue by txia77** [asynkron/protoactor-go#528]
Hi there, I noticed the following statements in the contributing guide:

"All Asynkron projects must include Asynkron copyright notices. Each project can choose between one of two approaches:

    i. All source files in the project must have a Asynkron copyright notice in the file header.
    ii. The Notices file for the project includes the Asynkron copyright notice and no other files contain copyright notices. See http://www.apache.org/legal/src-headers.html for instructions for managing this approach for copyrights.

Proto.Actor uses the first choice, having copyright notices in every file header."

However, hardly can I find any copyright notices in existing files, so may I ask what exactly is the correct way of doing this?

**Comment by DamnWidget** [comment]
```
Copyright (C) 2017 - 2021 Asynkron.se <http://www.asynkron.se>
```

You can find it in https://github.com/asynkron/protoactor-go/blob/10bc19881ad67edbec0531cfb22bc45557216e32/CONTRIBUTING.md#additional-guidelines

**Comment by txia77** [comment]
thanks that helps.
