### ISSUE TITLE
protoc-gen-gograin

### ISSUE THREAD

**Issue by sbulman** [asynkron/protoactor-go#582]
A couple of (hopefully) simple questions:

Which version of protoc-gen-gograin should I use for a new project. I assume V2, can you confirm?

How can I use google protobuf definitions in my proto file? If I import e.g.,  "google/protobuf/empty.proto" the code generator fails (well it writes out a partial file). I suspect I haven't got the correct protoc command. At the moment I am using

`protoc -I ./proto --gograinv2_out=paths=source_relative:./internal/pb ./proto/cluster/*.proto`

Thanks for any help

**Comment by DamnWidget** [comment]
You have to use v2 for any modern version of proto.actor. Proto.actor uses the gogo protobuf implementation, that is way faster than google's, the fact that the gogo version is used is both good and bad, mainly because doesn't seems to be maintained anymore. Anyway, staying on topic, to make that definition to work you must tell the protoc compiler where it can find the definition, in this case, there is a gogo version of it 

```
protoc -I=./proto -I=$GOPATH/src --gogoslick_out=\
Mgoogle/protobuf/empty.proto=github.com/gogo/protobuf/types,\:. ./proto/cluster/*.proto;
protoc -I ./proto --gograinv2_out=paths=source_relative:./internal/pb ./proto/cluster/*.proto
```

**Comment by sbulman** [comment]
@DamnWidget thanks for the answer. I tried out the suggested protoc commands above, an invalid file is still written.

This is my `proxy.proto` file

```
syntax = "proto3";

// The go grain code generator has poor handling of packages and go options
// This is the best options found so far. using go_options causes problems.
package cluster;

import "google/protobuf/empty.proto";

service ServiceProxy {
    rpc Start(google.protobuf.Empty) returns (google.protobuf.Empty);
    rpc Stop(google.protobuf.Empty) returns (google.protobuf.Empty);
}
```

and this is a snippet of the generated `proxy_protoactor.go` file

```
type ServiceProxy interface {
	Init(id string)
	Terminate()
	ReceiveDefault(ctx actor.Context)
	Start(*
```

the file is malformed and terminates after the `Start(*` so it looks related to the use of `google.protobuf.Empty`

**Comment by DamnWidget** [comment]
Yeah, look like that specific type is not implemented in `gogo`, but it is trivial, you can implement it yourself in the same proto file like:

```
syntax = "proto3";
package cluster;

message Empty {}

service ServiceProxy {
    rpc Start(Empty) returns (Empty);
    rpc Stop(Empty) returns (Empty);
}
```

You can see the definition of the Google's empty type [here](https://github.com/protocolbuffers/protobuf/blob/3f5fc4df1de8e12b2235c3006593e22d6993c3f5/src/google/protobuf/empty.proto)

**Comment by DamnWidget** [comment]
Reviewing the gogo repo better, I just noticed the empty type is there, I am not sure why it fails, I use other types as Struct with no issues

**Comment by DamnWidget** [comment]
I continued looking into this, the way that gograin works, messages that are not defined directly in the same proto file that the service that tries to use them can not be used as there is no data available about them at compilation time, even if the definition of the message has been compiled previously, that is why you can not use `google.protobuf.Empty` directly, actually, you can not use any message that is not wrapped into your own message in the same file definition at all.

**Comment by sbulman** [comment]
Thanks for looking. I can confirm that this generates a valid file (obviously I wouldn't do this, just wanted to test).

```
message StartServiceProxyRequest {
    google.protobuf.Empty test = 1;
}

service ServiceProxy {
    rpc Start(StartServiceProxyRequest) returns (StartServiceProxyResponse);
    rpc Stop(StopServiceProxyRequest) returns (StopServiceProxyResponse);
}
```
