### ISSUE TITLE
Port Gracefully Left

### ISSUE THREAD

**Issue by rogeralsing** [asynkron/protoactor-go#640]
https://github.com/asynkron/protoactor-dotnet/blob/dev/src/Proto.Cluster/Gossip/Gossiper.cs#L167

**Comment by ksankeerth** [comment]
Hi @rogeralsing, 
I'm trying to contribute to this issue but I'm facing some issues in building the project. The below are the errors.

` make build
github.com/asynkron/protoactor-go/persistence/protocb
persistence/protocb/provider.go:21:10: undefined: cbState
make: *** [build] Error 2`

After some research found that, `cbState struct` was commented [out](https://github.com/asynkron/protoactor-go/commit/4631be6fb4b8e951709795b56ff3f68389336e3b) recently and that causes the build failures. 

Sorry If I'm wrong, It's the first time I'm trying to build the protractor-go.Can you help me? Did I miss anything necessary steps while building?
