### ISSUE TITLE
Grain protogen generating invalid code

### ISSUE THREAD

**Issue by orktes** [asynkron/protoactor-go#648]
Hey!

I ran into a few issues with grain protogen and the generated code. I'm happy to personally tackle these once I have time but wanted to open a dialogue before I ambush you with a PR.

## Issue 1: The generator can't handle imports from other files or packages
In order to keep regular GRPC and Protoactor schemas and code in separate files (and preferably packages). The rationale is to be able to generate the protobuf (and regular GRPC) schemas to be used in all of our 30+ microservices while only utilising and importing protoactor only in a few places. The issue here is a that the grain generator expects everything to reside in a single file.

```proto
// messages types.proto
syntax = "proto3";

package foobar;

message FoobarRequest {}
message FoobarResponse {}
```

```proto
// actor.proto
syntax = "proto3";

import "types.proto";

package foobar;

service Foobar {
  rpc DoSomething(FoobarRequest) returns (FoobarResponse);
}
```

### Workaround
This can be worked around by creating a Wrapper message in the same file but it is kind of ugly.

```proto
// actor.proto
syntax = "proto3";

import "types.proto";

package foobar;

message FoobarRequestWrap {
  FoobarRequest req = 1;
}

message FoobarResponseWrap{
  FoobarResponse res = 1;
}


service Foobar {
  rpc DoSomething(FoobarRequestWrap) returns (FoobarResponseWrap);
}
```

### Possible fix
Utilising something like `google.golang.org/protobuf/compiler/protogen` will make it easy to both construct a message registry and then generate right package paths and go type names for the messages. 

## Issue 2: Referencing nested messages kills the generator
Kind of related to number 1. As the generator is expecting input and output messages to reside in the root of the file it wont traverse through the nested messages.

```proto
message Something {
  message Foobar {
  
  }
  message Barfoo {
  
  }
}

service Actor {
  rpc SendFoobar(Something.Foobar)  return (Something.Foobar)
}
```

## Issue 3: (Minor) The generator doesn't process the go_package option correctly

The go_package option can include an optional second part which is used for the package name

```proto
option go_package = "example.com/go-schemas;schemas";
```

### Outcome
The generator takes the everything after last / and cleans it up and generates and invalid package name.
```go
package go_schemas_schemas
```

## Issue 4: Can't have multiple files with different actors in the same package
Generator generates

```go
plog = logmod.New(logmod.InfoLevel, "[GRAIN][PACKAGENAME]")
```
To each file which will then cause a `plog redeclared in this block` error

### Possible fix
Generate these into a separate file per package

## Issue 5: (Major) the generator is not checking req.FileToGenerate when generating files
The current generator is generating code for all files in req.ProtoFile without checking if the file is part of req.FileToGenerate. This causes the generator to generate actor code for completely unrelated Service definitions that might exist in the imported files. This is problematic if one or many of the imports contains service definitions for normal GRPC services.

There is really no proper workaround which would not involve rewriting the included proto files which is not always possible as those could be third party.

## Fix
Check req.FileToGenerate before generating file.

**Comment by rogeralsing** [comment]
Resolved by #655
