### ISSUE TITLE
branch dev cannot build

### ISSUE THREAD

**Issue by linkerlin** [asynkron/protoactor-go#669]
$ go get ./...
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
go: module go.opentelemetry.io/otel/sdk/export/metric is deprecated: use go.opentelemetry.io/otel/sdk/metric instead.
$ make
# github.com/asynkron/protoactor-go/persistence/protocb
persistence/protocb/provider.go:21:10: undefined: cbState
make: *** [build] Error 2

**Comment by Tochemey** [comment]
@linkerlin the issue is that this file https://github.com/asynkron/protoactor-go/blob/dev/persistence/protocb/provider_state.go is commented out

**Comment by Tochemey** [comment]
I will open a PR shortly to address it

**Comment by Tochemey** [comment]
I have added a PR that fix #677
