### ISSUE TITLE
Gossip SendState received unknown response

### ISSUE THREAD

**Issue by mikai233** [asynkron/protoactor-go#705]
I run the _examples/cluster-basic program and change the provider to zk or etcd, i got **2022/08/09 14:35:03 ERROR [CLUSTER]     Gossip SendState received unknown response message=** log repeatedly
what's wrong?
![image](https://user-images.githubusercontent.com/49525397/183581713-fbf757a8-69fd-4651-a9d5-63a37875df74.png)

**Comment by cupen** [comment]
The go version's `cluster` doesn't work fine right now, and maybe  alpha stage in a long time.
You can just use `remote`, it's production-ready.

**Comment by mikai233** [comment]
> The go version's `cluster` doesn't work fine right now, and maybe alpha stage in a long time. You can just use `remote`, it's production-ready.

👌
