### ISSUE TITLE
Logic error

### ISSUE THREAD

**Issue by xiaoqinguo** [asynkron/protoactor-go#713]
Is it better to write this piece of code in else statement? if CAS return false, MailboxEmpty should not be called.

![Ai67dOfTN3](https://user-images.githubusercontent.com/9319187/186061335-2a8b077b-3059-497e-b2b0-5b1f14ca43e9.jpg)

**Comment by xiaoqinguo** [comment]
For further analysis, if actor is suspended, ms.MailboxEmpty will be called repeatedly after PostUserMessage.

**Comment by rogeralsing** [comment]
Fixed
