### ISSUE TITLE
The actor is deadlocked in some cases

### ISSUE THREAD

**Issue by chenxyzl** [asynkron/protoactor-go#795]
The actor is deadlocked in some cases
1. ActorA.Func1 call ActorB.Func2
2. ActorB.Func2 call ActorA.Func3
does actor support reentry?

**Comment by rogeralsing** [comment]
Yes you can use reentrancy:
https://github.com/asynkron/protoactor-go/blob/dev/actor/actor_context.go#L266

if you have a Future from a Request, you can pass that future into ReenterAfter, and it will continue in the actor context once the future is completed
