### ISSUE TITLE
When adding nodes, actors with the same id may be activated in multiple places

### ISSUE THREAD

**Issue by chenxyzl** [asynkron/protoactor-go#799]
**Describe the bug**
When adding nodes, actors with the same id may be activated in multiple places

**To Reproduce**
- start server node1
- start client then requset actor1
- start server node2
- start client then requset actor1
- actor1 will activated both node1 and node2（Half chance）

**Screenshots**
server node
![image](https://user-images.githubusercontent.com/11977514/216313918-339f128b-c6a5-400b-bb85-8152c87b97b0.png)
client
![image](https://user-images.githubusercontent.com/11977514/216314201-4e939653-fa6f-429e-bfd9-50fd63240758.png)

**Comment by chenxyzl** [comment]
when add new server node, function Rendezvous.GetByClusterIdentity may get a new address.
but old actor in old adress not terminate.

**Comment by rogeralsing** [comment]
Which identity lookup are you using here?

dist hash should poison actors that are no longer owned by the node on a topology change
https://github.com/asynkron/protoactor-go/blob/dev/cluster/identitylookup/disthash/placement_actor.go#L136

**Comment by chenxyzl** [comment]
> 

poisonPill message recived as 
![image](https://user-images.githubusercontent.com/11977514/216880526-1f18c3e9-9517-49bc-a460-fbe820d7827c.png)

**Comment by chenxyzl** [comment]
@rogeralsing 

when I add this code here, Terminate been called as expected
Is it necessary to add this code here？
``` go
case *actor.PoisonPill:
		a.ctx.Stop(a.ctx.Self())
```
![image](https://user-images.githubusercontent.com/11977514/216882245-fbdf58db-ff3d-4917-9851-ca0a08cd7f12.png)

If yes, it needs to be repaired on "protoc-gen-gograinv2"

**Comment by qazwsxedckll** [comment]
![image](https://github.com/asynkron/protoactor-go/assets/20088957/6237fbe2-2aec-495c-92e6-e4b3bb4bd5b3)
![image](https://github.com/asynkron/protoactor-go/assets/20088957/b3b5d79c-b3ce-4861-b3b5-f23192e7c61c)

> Which identity lookup are you using here?
> 
> dist hash should poison actors that are no longer owned by the node on a topology change https://github.com/asynkron/protoactor-go/blob/dev/cluster/identitylookup/disthash/placement_actor.go#L136

Actor is terminated before Poison been sent and never received.

**Comment by qazwsxedckll** [comment]
https://github.com/asynkron/protoactor-go/blob/291b4cf177db0288642d69b912ca86404f287e44/actor/actor_context.go#L351C21-L351C21

It get handled here if anyone is still interested.
