### ISSUE TITLE
Cluster Request return successful result but err is not nil

### ISSUE THREAD

**Issue by rendawudi** [asynkron/protoactor-go#800]
Bug:
cluster DefaultContext.Request has a selectloop
`

    resp, err = _context.RequestFuture(pid, message, ttl).Result()

    if err != nil {....}

    **break selectloop**
`

finally needs a break selectloop,otherwise the loop will start again and get timeout frome ctx.Done()

**Comment by lrweck** [comment]
I did a little debugging and found that the scheduler is creating tons and tons of goroutines (not all at the same time), but the time between messages just short enough for the the goroutine to finish, but not long enought that the goroutine is reused. I believe a reasonable amount of CPU is used there.
