### ISSUE TITLE
protoc-gen-gograinv2 fail to generate complete code if reference an imported message

### ISSUE THREAD

**Issue by globalflea** [asynkron/protoactor-go#826]
**Describe the bug**
Tried referring to `google.protobuf.Empty` as a param for a service.  The generated code is only partially completed.  Seems to die after hitting the `Empty` param

**To Reproduce**
Used this protobuf file:
```protobuf
syntax = "proto3";
package missing_feature_or_bug;

import "google/protobuf/empty.proto";

option go_package = "bug/report";

//message Empty{}
message Response{}

service SomeService {
  // rpc DoSomething(Empty) returns (Response);  // using local Empty{} works
  rpc DoSomething(google.protobuf.Empty) returns (Response);
}
```
The generated codes stopped at:
```go
// lots of code generated ...
... 

// SomeService interfaces the services available to the SomeService
type SomeService interface {
	Init(ctx cluster.GrainContext)
	Terminate(ctx cluster.GrainContext)
	ReceiveDefault(ctx cluster.GrainContext)
	DoSomething(*             // <----- abruptly ends here

```
However, if i comment off the `import "google/protobuf/empty.proto";` and uncomment the local `message Empty{}`, the
complete working code gets generated

So, it seems protoc-gen-gograinv2 can't handle imported messages ?

**Expected behavior**
A full protoactor code to be generated when using imported messages

**Screenshots**
None
**Additional context**
None

**Comment by Arttii** [comment]
A workaround I found for this was to wrap the imported message in a local message definition. Something like:
```
message DoSomethingRequest {
  importedMessage message=1;
}
```
