### ISSUE TITLE
Scheduling messages

### ISSUE THREAD

**Issue by rogeralsing** [asynkron/protoactor-go#87]
In Akka, there is the `ActorSystem.Scheduler`
In Proto.Actor, I would rather like to see some Scheduler interface, where we can provide different kinds of implementations.
e.g. in mem, cron job based etc.

Users can then either inject the scheduler they want into their actors, or, just have a package wide instance of whatever scheduler they want to use.

If we do this as part of the Proto.Actor library, I would like to see this as a separate package to keep the API surface as minimal as possible in the core actor package.

**Comment by bryanpkc** [comment]
I wrote a `Scheduler` interface for protoactor-go which is quite similar to the `AbstractScheduler` interface in Akka. I am curious what your thoughts are on a "cron job-based" scheduler. I know how cron works but I am not seeing how the interface (with methods like `schedule` and `scheduleOnce`) works with a cron table. Can you point me to an Akka example?

**Comment by rogeralsing** [comment]
In .NET we decided to go for a more opt-in model:
https://github.com/AsynkronIT/protoactor-dotnet/tree/dev/src/Schedulers/Proto.Scheduler.SimpleScheduler

It is an external package which can be evolved separately and do not require any internal changes to the core framework.

**Comment by nikoszoisse** [comment]
what about the go part? IS there a scheduler?
