### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by waeljammal** [asynkron/protoactor-go#904]
I'm looking to use it, just wondering if we need to fork it incase of bugs or if it's still maintained?

Is it in a decent enough state to use at least? Or still buggy? I ask because I don't see any releases or recent updates and we used to use Akka when we did Java but we are a go house now and would like to go back to actor model..

Thanks

**Comment by ccamel** [comment]
The project seems active - a new version [v0.3.0](https://github.com/asynkron/protoactor-go/releases/tag/0.3.0), was released just yesterday. However, I'm also wondering about its stability and maturity. I'm more used to [Erlang/OTP](https://www.erlang.org/) but am looking into Go alternatives supporting the actor model.

**Comment by Tochemey** [comment]
@ccamel this project may interest you then https://github.com/ergo-services/ergo. I played with it for some time and abandoned it because of the licensing. I also played with Proto-Actor Go but left it because their primary attention was on the .NET version.

**Comment by ccamel** [comment]
@Tochemey oh, that sounds great. I definitely need to play with [ergo](https://github.com/ergo-services/ergo). Thx! :+1:
