### ISSUE TITLE
Any plans of porting to other languages ?

### ISSUE THREAD

**Issue by tomaszchacuk** [asynkron/protoactor-go#94]
Hi,

I am interested in using proto-actor in my "system", as Akka cannot satisfy my needs of handling cross-platform actors.  My system would be developed as a plug-in model allowing to create plugins as actors that could be written in different languages. The core would be in C#, and GO i have out of the box. What about Java,Python,C++ ? Is there a support plan for it?

**Comment by rogeralsing** [comment]
We got the very first initial bits of Python pushed today. (nothing that works yet)

Python and Java should be fairly easy to do.
I've got far too little experience with C++ myself to know if this kind of port should be doable

**Comment by mrkaspa** [comment]
Is there a way to communicate with erlang's actors?

**Comment by rogeralsing** [comment]
@mrkaspa not yet.
I have been talking to some Erlang devs that are interested in building a protoactor-erlang.
