### ISSUE TITLE
How to do grain reentrance

### ISSUE THREAD

**Issue by qazwsxedckll** [asynkron/protoactor-go#980]
Request -> GrainA -> GrainB -> GrainA.

I find something like `ctx.RequestFuture` and `ctx.ReenterAfter` but I do not know how to do it in a cluster.

Based on my understanding, I can either write my own `type ContextProducer func(*Cluster) Context` which turns every request reenterable or I have to add a method to `type Context interface`

I found [https://github.com/asynkron/protoactor-dotnet/pull/913](url) but I cannot understand what is happening.

**Comment by rogeralsing** [comment]
In .NET, there are two methods generated, one which is more actor low level and can deal with reentrancy.
the default impl of this method just calls the RPC version. 

In the case where someone wants to use reentrancy, they can then override the low level method and handle it in there.
For Go, we need a different approach as we don´t have overrides in the same sense as in OOP

**Comment by qazwsxedckll** [comment]
Sorry but can you be a little more specific.

Do you mean two methods generated in `public class {{Name}}Client`? The one without `ISenderContext` is more low level? I cannot find any implementation of `RequestAsync<object>(_id, {{../Name}}Actor.Kind, gr, ct);` in `Proto.Cluster.Cluster`, only one with `ISenderContext`.

Or do you mean the vitural method `public virtual async Task {{Name}}({{LeadingParameterDefinition}}Action{{#if UseReturn}}<{{OutputName}}>{{/if}} respond, Action<string> onError)` which is meant to be overridden to handle reentrancy.
